name: yacht
description: Sail faster.
version: 0.0.1
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  analyzer: ^5.2.0
  build: ^2.0.2
  equatable: ^2.0.5
  http: ^0.13.3
  inflection3: ^0.5.3+2
  isar: ^3.0.5
  riverpod: ^2.1.3
  source_gen: ^1.0.1
  source_helper: ^1.3.2
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.3
  copy_with_extension: ^5.0.0
  copy_with_extension_gen: ^5.0.0
  isar_generator: ^3.0.5
  lints: ^2.0.0
  mockito: ^5.3.2
  test: ^1.16.0
