name: yacht
description: Sail faster.
version: 0.0.1
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  copy_with_extension: ^5.0.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  riverpod: ^2.1.3

dev_dependencies:
  build_runner: ^2.3.3
  copy_with_extension_gen: ^5.0.0
  isar_generator: ^3.0.5
  lints: ^2.0.0
  test: ^1.16.0
